/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPosturalRouteImport } from './routes/_authenticated.postural'
import { Route as AuthenticatedNovaAvaliacaoRouteImport } from './routes/_authenticated.nova-avaliacao'
import { Route as AuthenticatedExerciciosRouteImport } from './routes/_authenticated.exercicios'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedClinicasIndexRouteImport } from './routes/_authenticated.clinicas.index'
import { Route as AuthenticatedAvaliacoesIndexRouteImport } from './routes/_authenticated.avaliacoes.index'
import { Route as AuthenticatedAlunosIndexRouteImport } from './routes/_authenticated.alunos.index'
import { Route as AuthenticatedClinicasNovaRouteImport } from './routes/_authenticated.clinicas.nova'
import { Route as AuthenticatedClinicasIdRouteImport } from './routes/_authenticated.clinicas.$id'
import { Route as AuthenticatedAvaliacoesNovaRouteImport } from './routes/_authenticated.avaliacoes.nova'
import { Route as AuthenticatedAvaliacoesIdRouteImport } from './routes/_authenticated.avaliacoes.$id'
import { Route as AuthenticatedAlunosNovoRouteImport } from './routes/_authenticated.alunos.novo'
import { Route as AuthenticatedAlunosIdRouteImport } from './routes/_authenticated.alunos.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPosturalRoute = AuthenticatedPosturalRouteImport.update({
  id: '/postural',
  path: '/postural',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNovaAvaliacaoRoute =
  AuthenticatedNovaAvaliacaoRouteImport.update({
    id: '/nova-avaliacao',
    path: '/nova-avaliacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExerciciosRoute = AuthenticatedExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClinicasIndexRoute =
  AuthenticatedClinicasIndexRouteImport.update({
    id: '/clinicas/',
    path: '/clinicas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAvaliacoesIndexRoute =
  AuthenticatedAvaliacoesIndexRouteImport.update({
    id: '/avaliacoes/',
    path: '/avaliacoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlunosIndexRoute =
  AuthenticatedAlunosIndexRouteImport.update({
    id: '/alunos/',
    path: '/alunos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClinicasNovaRoute =
  AuthenticatedClinicasNovaRouteImport.update({
    id: '/clinicas/nova',
    path: '/clinicas/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClinicasIdRoute = AuthenticatedClinicasIdRouteImport.update({
  id: '/clinicas/$id',
  path: '/clinicas/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAvaliacoesNovaRoute =
  AuthenticatedAvaliacoesNovaRouteImport.update({
    id: '/avaliacoes/nova',
    path: '/avaliacoes/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAvaliacoesIdRoute =
  AuthenticatedAvaliacoesIdRouteImport.update({
    id: '/avaliacoes/$id',
    path: '/avaliacoes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlunosNovoRoute = AuthenticatedAlunosNovoRouteImport.update({
  id: '/alunos/novo',
  path: '/alunos/novo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlunosIdRoute = AuthenticatedAlunosIdRouteImport.update({
  id: '/alunos/$id',
  path: '/alunos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercicios': typeof AuthenticatedExerciciosRoute
  '/nova-avaliacao': typeof AuthenticatedNovaAvaliacaoRoute
  '/postural': typeof AuthenticatedPosturalRoute
  '/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/avaliacoes/$id': typeof AuthenticatedAvaliacoesIdRoute
  '/avaliacoes/nova': typeof AuthenticatedAvaliacoesNovaRoute
  '/clinicas/$id': typeof AuthenticatedClinicasIdRoute
  '/clinicas/nova': typeof AuthenticatedClinicasNovaRoute
  '/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/avaliacoes/': typeof AuthenticatedAvaliacoesIndexRoute
  '/clinicas/': typeof AuthenticatedClinicasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercicios': typeof AuthenticatedExerciciosRoute
  '/nova-avaliacao': typeof AuthenticatedNovaAvaliacaoRoute
  '/postural': typeof AuthenticatedPosturalRoute
  '/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/avaliacoes/$id': typeof AuthenticatedAvaliacoesIdRoute
  '/avaliacoes/nova': typeof AuthenticatedAvaliacoesNovaRoute
  '/clinicas/$id': typeof AuthenticatedClinicasIdRoute
  '/clinicas/nova': typeof AuthenticatedClinicasNovaRoute
  '/alunos': typeof AuthenticatedAlunosIndexRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesIndexRoute
  '/clinicas': typeof AuthenticatedClinicasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exercicios': typeof AuthenticatedExerciciosRoute
  '/_authenticated/nova-avaliacao': typeof AuthenticatedNovaAvaliacaoRoute
  '/_authenticated/postural': typeof AuthenticatedPosturalRoute
  '/_authenticated/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/_authenticated/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/_authenticated/avaliacoes/$id': typeof AuthenticatedAvaliacoesIdRoute
  '/_authenticated/avaliacoes/nova': typeof AuthenticatedAvaliacoesNovaRoute
  '/_authenticated/clinicas/$id': typeof AuthenticatedClinicasIdRoute
  '/_authenticated/clinicas/nova': typeof AuthenticatedClinicasNovaRoute
  '/_authenticated/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/_authenticated/avaliacoes/': typeof AuthenticatedAvaliacoesIndexRoute
  '/_authenticated/clinicas/': typeof AuthenticatedClinicasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/exercicios'
    | '/nova-avaliacao'
    | '/postural'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/avaliacoes/$id'
    | '/avaliacoes/nova'
    | '/clinicas/$id'
    | '/clinicas/nova'
    | '/alunos/'
    | '/avaliacoes/'
    | '/clinicas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/exercicios'
    | '/nova-avaliacao'
    | '/postural'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/avaliacoes/$id'
    | '/avaliacoes/nova'
    | '/clinicas/$id'
    | '/clinicas/nova'
    | '/alunos'
    | '/avaliacoes'
    | '/clinicas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/exercicios'
    | '/_authenticated/nova-avaliacao'
    | '/_authenticated/postural'
    | '/_authenticated/alunos/$id'
    | '/_authenticated/alunos/novo'
    | '/_authenticated/avaliacoes/$id'
    | '/_authenticated/avaliacoes/nova'
    | '/_authenticated/clinicas/$id'
    | '/_authenticated/clinicas/nova'
    | '/_authenticated/alunos/'
    | '/_authenticated/avaliacoes/'
    | '/_authenticated/clinicas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/postural': {
      id: '/_authenticated/postural'
      path: '/postural'
      fullPath: '/postural'
      preLoaderRoute: typeof AuthenticatedPosturalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nova-avaliacao': {
      id: '/_authenticated/nova-avaliacao'
      path: '/nova-avaliacao'
      fullPath: '/nova-avaliacao'
      preLoaderRoute: typeof AuthenticatedNovaAvaliacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exercicios': {
      id: '/_authenticated/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof AuthenticatedExerciciosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clinicas/': {
      id: '/_authenticated/clinicas/'
      path: '/clinicas'
      fullPath: '/clinicas/'
      preLoaderRoute: typeof AuthenticatedClinicasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/avaliacoes/': {
      id: '/_authenticated/avaliacoes/'
      path: '/avaliacoes'
      fullPath: '/avaliacoes/'
      preLoaderRoute: typeof AuthenticatedAvaliacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/': {
      id: '/_authenticated/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AuthenticatedAlunosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clinicas/nova': {
      id: '/_authenticated/clinicas/nova'
      path: '/clinicas/nova'
      fullPath: '/clinicas/nova'
      preLoaderRoute: typeof AuthenticatedClinicasNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clinicas/$id': {
      id: '/_authenticated/clinicas/$id'
      path: '/clinicas/$id'
      fullPath: '/clinicas/$id'
      preLoaderRoute: typeof AuthenticatedClinicasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/avaliacoes/nova': {
      id: '/_authenticated/avaliacoes/nova'
      path: '/avaliacoes/nova'
      fullPath: '/avaliacoes/nova'
      preLoaderRoute: typeof AuthenticatedAvaliacoesNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/avaliacoes/$id': {
      id: '/_authenticated/avaliacoes/$id'
      path: '/avaliacoes/$id'
      fullPath: '/avaliacoes/$id'
      preLoaderRoute: typeof AuthenticatedAvaliacoesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/novo': {
      id: '/_authenticated/alunos/novo'
      path: '/alunos/novo'
      fullPath: '/alunos/novo'
      preLoaderRoute: typeof AuthenticatedAlunosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/$id': {
      id: '/_authenticated/alunos/$id'
      path: '/alunos/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AuthenticatedAlunosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExerciciosRoute: typeof AuthenticatedExerciciosRoute
  AuthenticatedNovaAvaliacaoRoute: typeof AuthenticatedNovaAvaliacaoRoute
  AuthenticatedPosturalRoute: typeof AuthenticatedPosturalRoute
  AuthenticatedAlunosIdRoute: typeof AuthenticatedAlunosIdRoute
  AuthenticatedAlunosNovoRoute: typeof AuthenticatedAlunosNovoRoute
  AuthenticatedAvaliacoesIdRoute: typeof AuthenticatedAvaliacoesIdRoute
  AuthenticatedAvaliacoesNovaRoute: typeof AuthenticatedAvaliacoesNovaRoute
  AuthenticatedClinicasIdRoute: typeof AuthenticatedClinicasIdRoute
  AuthenticatedClinicasNovaRoute: typeof AuthenticatedClinicasNovaRoute
  AuthenticatedAlunosIndexRoute: typeof AuthenticatedAlunosIndexRoute
  AuthenticatedAvaliacoesIndexRoute: typeof AuthenticatedAvaliacoesIndexRoute
  AuthenticatedClinicasIndexRoute: typeof AuthenticatedClinicasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExerciciosRoute: AuthenticatedExerciciosRoute,
  AuthenticatedNovaAvaliacaoRoute: AuthenticatedNovaAvaliacaoRoute,
  AuthenticatedPosturalRoute: AuthenticatedPosturalRoute,
  AuthenticatedAlunosIdRoute: AuthenticatedAlunosIdRoute,
  AuthenticatedAlunosNovoRoute: AuthenticatedAlunosNovoRoute,
  AuthenticatedAvaliacoesIdRoute: AuthenticatedAvaliacoesIdRoute,
  AuthenticatedAvaliacoesNovaRoute: AuthenticatedAvaliacoesNovaRoute,
  AuthenticatedClinicasIdRoute: AuthenticatedClinicasIdRoute,
  AuthenticatedClinicasNovaRoute: AuthenticatedClinicasNovaRoute,
  AuthenticatedAlunosIndexRoute: AuthenticatedAlunosIndexRoute,
  AuthenticatedAvaliacoesIndexRoute: AuthenticatedAvaliacoesIndexRoute,
  AuthenticatedClinicasIndexRoute: AuthenticatedClinicasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
