/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NovaAvaliacaoRouteImport } from './routes/nova-avaliacao'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClinicasIndexRouteImport } from './routes/clinicas.index'
import { Route as AvaliacoesIndexRouteImport } from './routes/avaliacoes.index'
import { Route as AlunosIndexRouteImport } from './routes/alunos.index'
import { Route as ClinicasNovaRouteImport } from './routes/clinicas.nova'
import { Route as ClinicasIdRouteImport } from './routes/clinicas.$id'
import { Route as AvaliacoesNovaRouteImport } from './routes/avaliacoes.nova'
import { Route as AvaliacoesIdRouteImport } from './routes/avaliacoes.$id'
import { Route as AlunosNovoRouteImport } from './routes/alunos.novo'
import { Route as AlunosIdRouteImport } from './routes/alunos.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaAvaliacaoRoute = NovaAvaliacaoRouteImport.update({
  id: '/nova-avaliacao',
  path: '/nova-avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicasIndexRoute = ClinicasIndexRouteImport.update({
  id: '/clinicas/',
  path: '/clinicas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesIndexRoute = AvaliacoesIndexRouteImport.update({
  id: '/avaliacoes/',
  path: '/avaliacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosIndexRoute = AlunosIndexRouteImport.update({
  id: '/alunos/',
  path: '/alunos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicasNovaRoute = ClinicasNovaRouteImport.update({
  id: '/clinicas/nova',
  path: '/clinicas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicasIdRoute = ClinicasIdRouteImport.update({
  id: '/clinicas/$id',
  path: '/clinicas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesNovaRoute = AvaliacoesNovaRouteImport.update({
  id: '/avaliacoes/nova',
  path: '/avaliacoes/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesIdRoute = AvaliacoesIdRouteImport.update({
  id: '/avaliacoes/$id',
  path: '/avaliacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosNovoRoute = AlunosNovoRouteImport.update({
  id: '/alunos/novo',
  path: '/alunos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosIdRoute = AlunosIdRouteImport.update({
  id: '/alunos/$id',
  path: '/alunos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exercicios': typeof ExerciciosRoute
  '/nova-avaliacao': typeof NovaAvaliacaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/avaliacoes/$id': typeof AvaliacoesIdRoute
  '/avaliacoes/nova': typeof AvaliacoesNovaRoute
  '/clinicas/$id': typeof ClinicasIdRoute
  '/clinicas/nova': typeof ClinicasNovaRoute
  '/alunos/': typeof AlunosIndexRoute
  '/avaliacoes/': typeof AvaliacoesIndexRoute
  '/clinicas/': typeof ClinicasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exercicios': typeof ExerciciosRoute
  '/nova-avaliacao': typeof NovaAvaliacaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/avaliacoes/$id': typeof AvaliacoesIdRoute
  '/avaliacoes/nova': typeof AvaliacoesNovaRoute
  '/clinicas/$id': typeof ClinicasIdRoute
  '/clinicas/nova': typeof ClinicasNovaRoute
  '/alunos': typeof AlunosIndexRoute
  '/avaliacoes': typeof AvaliacoesIndexRoute
  '/clinicas': typeof ClinicasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exercicios': typeof ExerciciosRoute
  '/nova-avaliacao': typeof NovaAvaliacaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/avaliacoes/$id': typeof AvaliacoesIdRoute
  '/avaliacoes/nova': typeof AvaliacoesNovaRoute
  '/clinicas/$id': typeof ClinicasIdRoute
  '/clinicas/nova': typeof ClinicasNovaRoute
  '/alunos/': typeof AlunosIndexRoute
  '/avaliacoes/': typeof AvaliacoesIndexRoute
  '/clinicas/': typeof ClinicasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/exercicios'
    | '/nova-avaliacao'
    | '/sitemap.xml'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/avaliacoes/$id'
    | '/avaliacoes/nova'
    | '/clinicas/$id'
    | '/clinicas/nova'
    | '/alunos/'
    | '/avaliacoes/'
    | '/clinicas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/exercicios'
    | '/nova-avaliacao'
    | '/sitemap.xml'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/avaliacoes/$id'
    | '/avaliacoes/nova'
    | '/clinicas/$id'
    | '/clinicas/nova'
    | '/alunos'
    | '/avaliacoes'
    | '/clinicas'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/exercicios'
    | '/nova-avaliacao'
    | '/sitemap.xml'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/avaliacoes/$id'
    | '/avaliacoes/nova'
    | '/clinicas/$id'
    | '/clinicas/nova'
    | '/alunos/'
    | '/avaliacoes/'
    | '/clinicas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExerciciosRoute: typeof ExerciciosRoute
  NovaAvaliacaoRoute: typeof NovaAvaliacaoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AlunosIdRoute: typeof AlunosIdRoute
  AlunosNovoRoute: typeof AlunosNovoRoute
  AvaliacoesIdRoute: typeof AvaliacoesIdRoute
  AvaliacoesNovaRoute: typeof AvaliacoesNovaRoute
  ClinicasIdRoute: typeof ClinicasIdRoute
  ClinicasNovaRoute: typeof ClinicasNovaRoute
  AlunosIndexRoute: typeof AlunosIndexRoute
  AvaliacoesIndexRoute: typeof AvaliacoesIndexRoute
  ClinicasIndexRoute: typeof ClinicasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-avaliacao': {
      id: '/nova-avaliacao'
      path: '/nova-avaliacao'
      fullPath: '/nova-avaliacao'
      preLoaderRoute: typeof NovaAvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinicas/': {
      id: '/clinicas/'
      path: '/clinicas'
      fullPath: '/clinicas/'
      preLoaderRoute: typeof ClinicasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes/': {
      id: '/avaliacoes/'
      path: '/avaliacoes'
      fullPath: '/avaliacoes/'
      preLoaderRoute: typeof AvaliacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/': {
      id: '/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AlunosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinicas/nova': {
      id: '/clinicas/nova'
      path: '/clinicas/nova'
      fullPath: '/clinicas/nova'
      preLoaderRoute: typeof ClinicasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinicas/$id': {
      id: '/clinicas/$id'
      path: '/clinicas/$id'
      fullPath: '/clinicas/$id'
      preLoaderRoute: typeof ClinicasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes/nova': {
      id: '/avaliacoes/nova'
      path: '/avaliacoes/nova'
      fullPath: '/avaliacoes/nova'
      preLoaderRoute: typeof AvaliacoesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes/$id': {
      id: '/avaliacoes/$id'
      path: '/avaliacoes/$id'
      fullPath: '/avaliacoes/$id'
      preLoaderRoute: typeof AvaliacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/novo': {
      id: '/alunos/novo'
      path: '/alunos/novo'
      fullPath: '/alunos/novo'
      preLoaderRoute: typeof AlunosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/$id': {
      id: '/alunos/$id'
      path: '/alunos/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AlunosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExerciciosRoute: ExerciciosRoute,
  NovaAvaliacaoRoute: NovaAvaliacaoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AlunosIdRoute: AlunosIdRoute,
  AlunosNovoRoute: AlunosNovoRoute,
  AvaliacoesIdRoute: AvaliacoesIdRoute,
  AvaliacoesNovaRoute: AvaliacoesNovaRoute,
  ClinicasIdRoute: ClinicasIdRoute,
  ClinicasNovaRoute: ClinicasNovaRoute,
  AlunosIndexRoute: AlunosIndexRoute,
  AvaliacoesIndexRoute: AvaliacoesIndexRoute,
  ClinicasIndexRoute: ClinicasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
