/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedNovaAvaliacaoRouteImport } from './routes/_authenticated.nova-avaliacao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedAvaliacaoPosturalRouteImport } from './routes/_authenticated.avaliacao-postural'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAvaliacoesIndexRouteImport } from './routes/_authenticated.avaliacoes.index'
import { Route as AuthenticatedAlunosIndexRouteImport } from './routes/_authenticated.alunos.index'
import { Route as AuthenticatedRelatoriosIdRouteImport } from './routes/_authenticated.relatorios.$id'
import { Route as AuthenticatedAvaliacoesNovaRouteImport } from './routes/_authenticated.avaliacoes.nova'
import { Route as AuthenticatedAvaliacoesIdRouteImport } from './routes/_authenticated.avaliacoes.$id'
import { Route as AuthenticatedAlunosNovoRouteImport } from './routes/_authenticated.alunos.novo'
import { Route as AuthenticatedAlunosIdRouteImport } from './routes/_authenticated.alunos.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNovaAvaliacaoRoute =
  AuthenticatedNovaAvaliacaoRouteImport.update({
    id: '/nova-avaliacao',
    path: '/nova-avaliacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAvaliacaoPosturalRoute =
  AuthenticatedAvaliacaoPosturalRouteImport.update({
    id: '/avaliacao-postural',
    path: '/avaliacao-postural',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAvaliacoesIndexRoute =
  AuthenticatedAvaliacoesIndexRouteImport.update({
    id: '/avaliacoes/',
    path: '/avaliacoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlunosIndexRoute =
  AuthenticatedAlunosIndexRouteImport.update({
    id: '/alunos/',
    path: '/alunos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosIdRoute =
  AuthenticatedRelatoriosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedAvaliacoesNovaRoute =
  AuthenticatedAvaliacoesNovaRouteImport.update({
    id: '/avaliacoes/nova',
    path: '/avaliacoes/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAvaliacoesIdRoute =
  AuthenticatedAvaliacoesIdRouteImport.update({
    id: '/avaliacoes/$id',
    path: '/avaliacoes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlunosNovoRoute = AuthenticatedAlunosNovoRouteImport.update({
  id: '/alunos/novo',
  path: '/alunos/novo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlunosIdRoute = AuthenticatedAlunosIdRouteImport.update({
  id: '/alunos/$id',
  path: '/alunos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/avaliacao-postural': typeof AuthenticatedAvaliacaoPosturalRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/nova-avaliacao': typeof AuthenticatedNovaAvaliacaoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/avaliacoes/$id': typeof AuthenticatedAvaliacoesIdRoute
  '/avaliacoes/nova': typeof AuthenticatedAvaliacoesNovaRoute
  '/relatorios/$id': typeof AuthenticatedRelatoriosIdRoute
  '/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/avaliacoes/': typeof AuthenticatedAvaliacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/avaliacao-postural': typeof AuthenticatedAvaliacaoPosturalRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/nova-avaliacao': typeof AuthenticatedNovaAvaliacaoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/avaliacoes/$id': typeof AuthenticatedAvaliacoesIdRoute
  '/avaliacoes/nova': typeof AuthenticatedAvaliacoesNovaRoute
  '/relatorios/$id': typeof AuthenticatedRelatoriosIdRoute
  '/alunos': typeof AuthenticatedAlunosIndexRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/avaliacao-postural': typeof AuthenticatedAvaliacaoPosturalRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/nova-avaliacao': typeof AuthenticatedNovaAvaliacaoRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/_authenticated/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/_authenticated/avaliacoes/$id': typeof AuthenticatedAvaliacoesIdRoute
  '/_authenticated/avaliacoes/nova': typeof AuthenticatedAvaliacoesNovaRoute
  '/_authenticated/relatorios/$id': typeof AuthenticatedRelatoriosIdRoute
  '/_authenticated/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/_authenticated/avaliacoes/': typeof AuthenticatedAvaliacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/avaliacao-postural'
    | '/configuracoes'
    | '/dashboard'
    | '/nova-avaliacao'
    | '/onboarding'
    | '/relatorios'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/avaliacoes/$id'
    | '/avaliacoes/nova'
    | '/relatorios/$id'
    | '/alunos/'
    | '/avaliacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/avaliacao-postural'
    | '/configuracoes'
    | '/dashboard'
    | '/nova-avaliacao'
    | '/onboarding'
    | '/relatorios'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/alunos/$id'
    | '/alunos/novo'
    | '/avaliacoes/$id'
    | '/avaliacoes/nova'
    | '/relatorios/$id'
    | '/alunos'
    | '/avaliacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/avaliacao-postural'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/nova-avaliacao'
    | '/_authenticated/onboarding'
    | '/_authenticated/relatorios'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/alunos/$id'
    | '/_authenticated/alunos/novo'
    | '/_authenticated/avaliacoes/$id'
    | '/_authenticated/avaliacoes/nova'
    | '/_authenticated/relatorios/$id'
    | '/_authenticated/alunos/'
    | '/_authenticated/avaliacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nova-avaliacao': {
      id: '/_authenticated/nova-avaliacao'
      path: '/nova-avaliacao'
      fullPath: '/nova-avaliacao'
      preLoaderRoute: typeof AuthenticatedNovaAvaliacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/avaliacao-postural': {
      id: '/_authenticated/avaliacao-postural'
      path: '/avaliacao-postural'
      fullPath: '/avaliacao-postural'
      preLoaderRoute: typeof AuthenticatedAvaliacaoPosturalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/avaliacoes/': {
      id: '/_authenticated/avaliacoes/'
      path: '/avaliacoes'
      fullPath: '/avaliacoes/'
      preLoaderRoute: typeof AuthenticatedAvaliacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/': {
      id: '/_authenticated/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AuthenticatedAlunosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios/$id': {
      id: '/_authenticated/relatorios/$id'
      path: '/$id'
      fullPath: '/relatorios/$id'
      preLoaderRoute: typeof AuthenticatedRelatoriosIdRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/avaliacoes/nova': {
      id: '/_authenticated/avaliacoes/nova'
      path: '/avaliacoes/nova'
      fullPath: '/avaliacoes/nova'
      preLoaderRoute: typeof AuthenticatedAvaliacoesNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/avaliacoes/$id': {
      id: '/_authenticated/avaliacoes/$id'
      path: '/avaliacoes/$id'
      fullPath: '/avaliacoes/$id'
      preLoaderRoute: typeof AuthenticatedAvaliacoesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/novo': {
      id: '/_authenticated/alunos/novo'
      path: '/alunos/novo'
      fullPath: '/alunos/novo'
      preLoaderRoute: typeof AuthenticatedAlunosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/$id': {
      id: '/_authenticated/alunos/$id'
      path: '/alunos/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AuthenticatedAlunosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRelatoriosRouteChildren {
  AuthenticatedRelatoriosIdRoute: typeof AuthenticatedRelatoriosIdRoute
}

const AuthenticatedRelatoriosRouteChildren: AuthenticatedRelatoriosRouteChildren =
  {
    AuthenticatedRelatoriosIdRoute: AuthenticatedRelatoriosIdRoute,
  }

const AuthenticatedRelatoriosRouteWithChildren =
  AuthenticatedRelatoriosRoute._addFileChildren(
    AuthenticatedRelatoriosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAvaliacaoPosturalRoute: typeof AuthenticatedAvaliacaoPosturalRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNovaAvaliacaoRoute: typeof AuthenticatedNovaAvaliacaoRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRouteWithChildren
  AuthenticatedAlunosIdRoute: typeof AuthenticatedAlunosIdRoute
  AuthenticatedAlunosNovoRoute: typeof AuthenticatedAlunosNovoRoute
  AuthenticatedAvaliacoesIdRoute: typeof AuthenticatedAvaliacoesIdRoute
  AuthenticatedAvaliacoesNovaRoute: typeof AuthenticatedAvaliacoesNovaRoute
  AuthenticatedAlunosIndexRoute: typeof AuthenticatedAlunosIndexRoute
  AuthenticatedAvaliacoesIndexRoute: typeof AuthenticatedAvaliacoesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAvaliacaoPosturalRoute: AuthenticatedAvaliacaoPosturalRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNovaAvaliacaoRoute: AuthenticatedNovaAvaliacaoRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRouteWithChildren,
  AuthenticatedAlunosIdRoute: AuthenticatedAlunosIdRoute,
  AuthenticatedAlunosNovoRoute: AuthenticatedAlunosNovoRoute,
  AuthenticatedAvaliacoesIdRoute: AuthenticatedAvaliacoesIdRoute,
  AuthenticatedAvaliacoesNovaRoute: AuthenticatedAvaliacoesNovaRoute,
  AuthenticatedAlunosIndexRoute: AuthenticatedAlunosIndexRoute,
  AuthenticatedAvaliacoesIndexRoute: AuthenticatedAvaliacoesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
