-- Cria catálogo global de exercícios (leitura autenticada) e amplia exercise_results
create table if not exists public.exercise_library (
  id text primary key,
  name_pt text not null,
  name_en text,
  method_family text,
  equipment text not null,
  level text not null,
  position text,
  primary_goal text,
  clinical_focus text,
  setup text,
  execution text,
  key_cues text,
  vision_metrics text,
  common_compensations text,
  red_flags text,
  regression text,
  progression text,
  image_ref text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

grant select on public.exercise_library to authenticated;
grant all on public.exercise_library to service_role;

alter table public.exercise_library enable row level security;

drop policy if exists "ExerciseLibrary: read for authenticated" on public.exercise_library;
create policy "ExerciseLibrary: read for authenticated" on public.exercise_library
  for select to authenticated using (is_active = true);

create index if not exists idx_exlib_equipment on public.exercise_library(equipment);
create index if not exists idx_exlib_level on public.exercise_library(level);
create index if not exists idx_exlib_primary_goal on public.exercise_library(primary_goal);

drop trigger if exists tg_exercise_library_updated_at on public.exercise_library;
create trigger tg_exercise_library_updated_at before update on public.exercise_library
  for each row execute function public.tg_set_updated_at();

-- Amplia exercise_results
alter table public.exercise_results
  add column if not exists support_level smallint,
  add column if not exists library_exercise_id text references public.exercise_library(id) on delete set null,
  add column if not exists generated_by text not null default 'professional';

alter table public.exercise_results
  drop constraint if exists exercise_results_support_level_chk;
alter table public.exercise_results
  add constraint exercise_results_support_level_chk check (support_level is null or (support_level between 0 and 3));

-- Seed do catálogo (idempotente)
insert into public.exercise_library (id, name_pt, name_en, method_family, equipment, level, position, primary_goal, clinical_focus, setup, execution, key_cues, vision_metrics, common_compensations, red_flags, regression, progression, image_ref)
values
('mat_hundred', 'Cem', 'The Hundred', 'Mat clássico/contemporâneo', 'Mat', 'intermediario', 'decúbito dorsal com tronco flexionado', 'ativação de centro e coordenação respiratória', 'controle cervical, core, resistência postural', 'deitar, elevar pernas conforme tolerância, flexionar cabeça e tronco', 'bombear braços em pequena amplitude coordenando respiração', 'costelas fechadas, pescoço longo, pelve estável', 'ângulo cervical, flexão de tronco, altura das pernas, estabilidade pélvica', 'protrusão cervical, prender respiração, hiperlordose, tensão em ombros', 'dor cervical, tontura, dispneia, dor lombar irritável', 'joelhos flexionados e cabeça apoiada', 'pernas estendidas em menor ângulo', NULL),
('mat_roll_up', 'Rolamento para cima', 'Roll Up', 'Mat clássico/contemporâneo', 'Mat', 'intermediario', 'decúbito dorsal para sentado', 'mobilidade segmentar de coluna', 'flexibilidade posterior, dissociação coluna-pelve', 'deitar com braços acima da cabeça ou à frente', 'enrolar a coluna até sentar e flexionar à frente', 'subir vértebra por vértebra, evitar impulso', 'trajetória tronco, velocidade, simetria de membros, flexão segmentar', 'impulso de braços, elevação dos pés, rigidez lombar', 'dor lombar aguda, osteoporose importante sem adaptação', 'half roll back', 'roll up completo com controle', NULL),
('mat_pelvic_curl', 'Ponte articulada', 'Pelvic Curl', 'Mat contemporâneo/clínico', 'Mat', 'iniciante', 'decúbito dorsal joelhos flexionados', 'mobilidade lombopélvica e extensão de quadril', 'controle lombar, glúteos, isquiotibiais', 'deitar com pés paralelos e joelhos alinhados', 'retroversão pélvica e elevação gradual da coluna', 'subir sem abrir joelhos, distribuir carga nos pés', 'altura pélvica, simetria ASIS, alinhamento joelho-pé', 'joelhos em valgo, hiperextensão lombar, apoio assimétrico', 'dor irradiada, cãibra intensa, pós-operatório sem liberação', 'ponte baixa', 'single leg bridge', NULL),
('mat_single_leg_stretch', 'Alongamento unilateral de perna', 'Single Leg Stretch', 'Mat clássico', 'Mat', 'intermediario', 'decúbito dorsal tronco flexionado', 'coordenação core-quadril', 'controle abdominal e dissociação MMII', 'tronco flexionado, uma perna próxima ao peito, outra estendida', 'alternar pernas mantendo tronco estável', 'pelve quieta, cotovelos abertos, respiração fluida', 'estabilidade pélvica, ângulo do joelho, altura da perna', 'balanço de tronco, puxar pescoço, lombar arqueada', 'dor cervical/lombar, fraqueza abdominal importante', 'cabeça apoiada', 'double leg stretch', NULL),
('mat_double_leg_stretch', 'Alongamento duplo de pernas', 'Double Leg Stretch', 'Mat clássico', 'Mat', 'intermediario', 'decúbito dorsal tronco flexionado', 'controle de core em alavanca longa', 'força abdominal e coordenação', 'joelhos ao peito, mãos nos tornozelos ou tíbias', 'estender braços e pernas, retornar em círculo', 'manter costelas baixas e pelve neutra/estável', 'ângulo pernas, abertura costal, estabilidade pélvica', 'pernas baixas demais, tensão cervical, perda de pelve', 'dor lombar/cervical', 'reduzir amplitude', 'pernas mais baixas e longas', NULL),
('mat_spine_stretch', 'Alongamento da coluna', 'Spine Stretch Forward', 'Mat clássico/contemporâneo', 'Mat', 'iniciante', 'sentado pernas afastadas', 'mobilidade axial e flexão torácica', 'cadeia posterior, controle respiratório', 'sentar alto com pernas afastadas e braços à frente', 'flexionar coluna para frente como curva longa', 'crescer antes de flexionar, evitar colapsar lombar', 'ângulo tronco, flexão torácica, simetria ombros', 'retroverter demais, elevar ombros, flexionar joelhos', 'dor ciática irritável, osteoporose sem adaptação', 'sentar em apoio elevado', 'adicionar rotação', NULL),
('mat_swan_prep', 'Preparação para cisne', 'Swan Prep', 'Mat contemporâneo/clínico', 'Mat', 'iniciante', 'decúbito ventral', 'extensão torácica e controle escapular', 'cadeia posterior, mobilidade torácica', 'deitar de barriga para baixo, mãos abaixo dos ombros', 'elevar tronco com extensão suave mantendo pelve no solo', 'alongar nuca, peito aberto, escápulas baixas', 'extensão torácica, hiperextensão lombar, posição cervical', 'forçar braços, comprimir lombar, elevar ombros', 'dor lombar facetária irritável, tontura', 'mini extensão com mãos fora do solo', 'swan dive modificado', NULL),
('mat_swimming', 'Natação', 'Swimming', 'Mat clássico', 'Mat', 'intermediario', 'decúbito ventral', 'extensão global e coordenação cruzada', 'cadeia posterior, controle lombopélvico', 'deitar em prono com braços à frente', 'alternar braços e pernas em pequena amplitude', 'movimento longo, costelas controladas, olhar para baixo', 'amplitude alternada, simetria, estabilidade pélvica', 'chutar alto demais, cervical em extensão, lombar comprimida', 'dor lombar, dor cervical, pós-operatório', 'elevar apenas braços ou pernas', 'maior tempo/cadência', NULL),
('mat_side_kick', 'Chute lateral', 'Side Kick Series', 'Mat clássico', 'Mat', 'intermediario', 'decúbito lateral', 'estabilidade pélvica e controle de quadril', 'glúteo médio, dissociação coxo-femoral', 'deitar lateral, corpo alinhado, mão apoiando cabeça', 'mobilizar perna superior mantendo pelve estável', 'quadril empilhado, tronco quieto, pé ativo', 'oscilação pélvica, amplitude de quadril, alinhamento tronco', 'rolar para frente/trás, tensão cervical, compensar lombar', 'dor lateral de quadril intensa, instabilidade', 'joelho flexionado', 'círculos e variações avançadas', NULL),
('mat_teaser_prep', 'Preparação para teaser', 'Teaser Prep', 'Mat clássico/contemporâneo', 'Mat', 'avancado', 'sentado/decúbito com pernas elevadas', 'controle global de core e equilíbrio', 'força abdominal, flexores de quadril com controle', 'iniciar sentado com joelhos flexionados ou supino', 'subir tronco e pernas em V controlado', 'esterno aberto, pelve controlada, sem tranco', 'ângulo tronco-coxa, estabilidade, simetria', 'usar impulso, prender respiração, colapsar lombar', 'dor lombar/cervical, hérnia irritável', 'half teaser', 'teaser completo', NULL),
('mat_plank', 'Prancha', 'Plank', 'Mat contemporâneo/clínico', 'Mat', 'intermediario', 'apoio mãos/antebraços e pés', 'estabilidade de core e cintura escapular', 'anti-extensão, ombro, controle global', 'alinhar ombros, quadril e tornozelos', 'manter posição por tempo ou com variações', 'empurrar o chão, costelas para dentro, glúteos ativos', 'linha ombro-quadril-tornozelo, queda pélvica, escápulas', 'quadril baixo/alto, cabeça caída, escápula alada', 'dor punho/ombro/lombar, hipertensão não controlada', 'joelhos apoiados', 'leg pull front', NULL),
('mat_cat_stretch', 'Gato', 'Cat Stretch', 'Mat clínico/contemporâneo', 'Mat', 'iniciante', 'quatro apoios', 'mobilidade segmentar de coluna', 'controle respiratório e dor lombar leve', 'alinhar mãos abaixo dos ombros e joelhos abaixo do quadril', 'alternar flexão e extensão de coluna', 'movimento suave, distribuir pela coluna toda', 'curvatura coluna, amplitude pélvica, simetria de apoio', 'movimento só cervical/lombar, cotovelos travados', 'dor aguda, tontura', 'menor amplitude', 'adicionar rotação torácica', NULL),
('ref_footwork', 'Trabalho de pés no Reformer', 'Reformer Footwork', 'Reformer', 'Reformer', 'iniciante', 'decúbito dorsal com pés na barra', 'força MMII e alinhamento em cadeia fechada', 'quadril-joelho-pé, controle de carga', 'deitar no carrinho, pés paralelos na footbar, molas adequadas', 'empurrar e retornar carrinho com controle', 'joelhos seguem segundo dedo, pelve neutra, retorno freado', 'ângulo joelho, valgo/varo, simetria, controle excêntrico', 'valgo dinâmico, travar joelhos, descontrole no retorno', 'dor aguda no joelho/quadril, pós-operatório sem liberação', 'menor resistência/amplitude', 'variações ponta/calcanhar/unilateral', NULL),
('ref_leg_circles', 'Círculos de pernas nas alças', 'Leg Circles', 'Reformer', 'Reformer', 'iniciante-intermediario', 'decúbito dorsal com pés nas alças', 'mobilidade de quadril com estabilidade pélvica', 'controle lombo-pélvico, amplitude de quadril', 'colocar pés nas alças, pernas elevadas', 'realizar círculos simétricos sem mover pelve', 'círculos iguais, sacro pesado, respiração fluida', 'trajetória dos tornozelos, assimetria, inclinação pélvica', 'amplitude excessiva, lombar arqueada, joelhos hiperestendidos', 'dor lombar/virilha, prótese recente sem liberação', 'círculos pequenos', 'maior amplitude e coordenação', NULL),
('ref_hundred', 'Cem no Reformer', 'Hundred on Reformer', 'Reformer', 'Reformer', 'intermediario', 'decúbito dorsal com alças', 'coordenação respiratória e resistência de core', 'controle de tronco contra resistência', 'deitar, segurar alças, pernas em tabletop ou estendidas', 'flexionar tronco e bombear braços tensionando molas', 'ombros baixos, alças estáveis, pelve quieta', 'ângulo tronco, tensão braços, altura pernas', 'elevar ombros, mexer carrinho, perder pelve', 'dor cervical, tontura, dispneia', 'cabeça apoiada', 'pernas estendidas', NULL),
('ref_short_spine', 'Coluna curta', 'Short Spine Massage', 'Reformer', 'Reformer', 'intermediario', 'decúbito dorsal com pés nas alças', 'mobilidade de coluna e flexibilidade posterior', 'articulação vertebral e controle abdominal', 'pés nas alças, pernas estendidas', 'elevar pelve, flexionar joelhos, articular descida', 'subir e descer com controle, não jogar peso no pescoço', 'elevação pélvica, flexão cervical, controle da descida', 'apoio excessivo cervical, velocidade alta, assimetria', 'osteoporose, cervicalgia importante, glaucoma não controlado', 'frog/leg circles', 'variações avançadas', NULL),
('ref_bridging', 'Ponte no Reformer', 'Bridging on Reformer', 'Reformer', 'Reformer', 'iniciante-intermediario', 'decúbito dorsal pés na barra', 'extensão de quadril e controle pélvico', 'glúteos, isquiotibiais, estabilidade lombar', 'pés na footbar, pelve neutra', 'elevar quadril e manter carrinho estável ou mover', 'joelhos alinhados, coluna longa, não compensar lombar', 'altura pélvica, deslocamento carrinho, valgo joelho', 'assimetria, hiperextensão lombar, cãibra', 'dor lombar/joelho', 'ponte no mat', 'ponte unilateral', NULL),
('ref_long_stretch', 'Alongamento longo', 'Long Stretch', 'Reformer', 'Reformer', 'avancado', 'prancha com mãos na barra e pés no apoio', 'estabilidade global e controle escapular', 'core, ombros, cadeia anterior', 'posição de prancha no Reformer', 'empurrar carrinho e retornar mantendo alinhamento', 'corpo em bloco, escápulas estáveis, abdome ativo', 'linha corporal, escápula, deslocamento carrinho', 'quadril cai, ombros sobem, cotovelos travam', 'dor ombro/punho/lombar, baixa tolerância', 'plank no mat', 'up stretch', NULL),
('ref_scooter', 'Patinete', 'Scooter', 'Reformer', 'Reformer', 'intermediario', 'em pé/afundo com um pé no carrinho', 'controle unilateral de quadril e joelho', 'glúteos, equilíbrio, alinhamento MMII', 'um pé no solo/plataforma e outro no carrinho', 'empurrar carrinho com perna móvel e retornar', 'pelve nivelada, joelho alinhado, tronco estável', 'valgo joelho, inclinação pélvica, controle retorno', 'tronco colapsa, pé roda, joelho entra', 'dor joelho/quadril, instabilidade', 'menor mola/amplitude', 'variação sem apoio', NULL),
('ref_side_splits', 'Aberturas laterais', 'Side Splits', 'Reformer', 'Reformer', 'avancado', 'em pé com pernas afastadas no carrinho/plataforma', 'controle frontal, adutores e estabilidade', 'equilíbrio, força excêntrica, simetria', 'ficar em pé com segurança e molas adequadas', 'abrir e fechar pernas mantendo eixo', 'coluna alta, joelhos macios, peso distribuído', 'distância entre pés, simetria, oscilação tronco', 'travamento joelho, medo/rigidez, assimetria', 'risco de queda, dor adutor/joelho', 'standing hip abduction com apoio', 'variações com braços', NULL),
('cad_roll_down', 'Rolamento com barra', 'Roll Down Bar', 'Cadillac', 'Cadillac', 'iniciante-intermediario', 'sentado segurando barra com molas', 'mobilidade de coluna e controle excêntrico', 'flexão segmentar, respiração, core', 'sentar alto segurando barra', 'enrolar para trás e retornar segmentando coluna', 'usar molas como assistência, não como tranco', 'ângulo tronco, segmentação, simetria ombros', 'elevar ombros, colapsar peito, puxar com braços', 'dor lombar/cervical aguda', 'menor amplitude', 'roll up no mat', NULL),
('cad_leg_springs', 'Molas de pernas', 'Leg Springs', 'Cadillac', 'Cadillac', 'iniciante-intermediario', 'decúbito dorsal com molas nos pés', 'controle de quadril e pelve', 'mobilidade, força de quadril, estabilidade lombo-pélvica', 'prender alças nos pés e ajustar molas', 'abrir, fechar, abaixar ou circular pernas', 'pelve pesada, trajetórias simétricas, controle retorno', 'trajetória pés, inclinação pélvica, amplitude', 'hiperlordose, assimetria, tensionar pescoço', 'dor lombar/virilha', 'menor amplitude', 'círculos maiores e coordenação', NULL),
('cad_arm_springs', 'Molas de braços', 'Arm Springs', 'Cadillac', 'Cadillac', 'iniciante-intermediario', 'decúbito dorsal/sentado', 'força de membros superiores e controle escapular', 'ombro, escápula, postura torácica', 'segurar alças com molas adequadas', 'realizar flexão/extensão/abdução controlada', 'ombros longe das orelhas, costelas controladas', 'elevação escapular, simetria braços, costelas', 'compensar cervical, abrir costelas, punhos rígidos', 'dor ombro aguda, parestesia', 'carga leve', 'sentado/ajoelhado', NULL),
('cad_push_through', 'Empurrar através da barra', 'Push Through', 'Cadillac', 'Cadillac', 'intermediario', 'sentado ou supino com barra', 'mobilidade coluna/ombro e controle de força', 'cadeia anterior/posterior, coordenação', 'ajustar barra e molas com segurança', 'empurrar a barra com controle conforme variação', 'manter alinhamento, respeitar amplitude segura', 'amplitude ombro, coluna, controle barra', 'perder controle da barra, ombros elevados', 'risco se mola/barra mal ajustada', 'variação com menor mola', 'variações avançadas', NULL),
('cad_monkey', 'Macaco', 'Monkey', 'Cadillac', 'Cadillac', 'avancado', 'supino com pés na barra', 'flexibilidade posterior e controle de coluna', 'isquiotibiais, coluna, coordenação', 'deitar com pés na barra e mãos segurando apoio', 'estender pernas e articular coluna conforme variação', 'controle total, não forçar joelhos/cervical', 'ângulo joelho/quadril, flexão coluna, simetria', 'forçar alongamento, travar joelhos, tensão cervical', 'osteoporose, dor ciática irritável', 'alongamento assistido simples', 'monkey completo', NULL),
('chair_footwork', 'Trabalho de pés na Chair', 'Chair Footwork', 'Chair', 'Wunda/Stability Chair', 'intermediario', 'sentado com pés no pedal', 'força MMII e controle postural', 'quadríceps, glúteos, alinhamento joelho-pé', 'sentar alto, pés no pedal', 'pressionar e controlar retorno do pedal', 'coluna alta, joelhos alinhados, retorno freado', 'ângulo joelho, simetria pedal, postura tronco', 'desabar tronco, joelhos entram, bater pedal', 'dor aguda joelho/quadril', 'menor mola/amplitude', 'unilateral', NULL),
('chair_pike', 'Pike na Chair', 'Pike', 'Chair', 'Wunda/Stability Chair', 'avancado', 'em pé sobre pedal/mãos na cadeira', 'força de core e flexão de tronco', 'controle abdominal, ombros, equilíbrio', 'mãos apoiadas, pés no pedal', 'elevar pelve puxando pedal com controle', 'empurrar a cadeira, coluna em C, ombros estáveis', 'altura pélvica, escápula, simetria', 'usar impulso, colapsar ombros, perder pedal', 'dor punho/ombro/lombar, risco de queda', 'elephant no Reformer', 'pike avançado', NULL),
('chair_mermaid', 'Sereia na Chair', 'Mermaid on Chair', 'Chair', 'Wunda/Stability Chair', 'intermediario', 'sentado lateral', 'mobilidade lateral da coluna', 'inclinação lateral, respiração, ombro', 'sentar lateral com mão no pedal', 'pressionar pedal inclinando tronco lateralmente', 'alongar costelas, manter pelve pesada', 'ângulo lateral, posição ombro, simetria', 'rodar tronco, elevar ombro, colapsar lombar', 'dor ombro/costela aguda', 'mermaid no mat', 'maior amplitude', NULL),
('chair_step_up', 'Subida na Chair', 'Step Up', 'Chair', 'Wunda/Stability Chair', 'avancado', 'em pé com um pé no pedal', 'força unilateral e equilíbrio', 'glúteo, quadríceps, controle frontal', 'um pé no pedal, mãos em apoio se necessário', 'pressionar pedal e controlar retorno/subida', 'joelho acompanha pé, tronco alto, pelve nivelada', 'valgo dinâmico, inclinação tronco, controle pedal', 'joelho entra, impulso, perda equilíbrio', 'risco de queda, dor joelho/quadril', 'apoio manual', 'sem apoio/variações', NULL),
('barrel_swan', 'Cisne no Barrel', 'Swan on Barrel', 'Barrel', 'Ladder Barrel/Spine Corrector', 'intermediario', 'decúbito ventral sobre barrel', 'extensão torácica e cadeia posterior', 'mobilidade coluna, glúteos, controle lombar', 'posicionar tronco sobre barrel com apoio seguro', 'realizar extensão controlada do tronco', 'alongar pelo topo da cabeça, distribuir extensão', 'ângulo extensão, cervical, simetria escápulas', 'hiperextensão lombar, ombros tensos', 'dor lombar/cervical', 'mini swan no mat', 'swan completo', NULL),
('barrel_side_bend', 'Inclinação lateral no Barrel', 'Side Bend on Barrel', 'Barrel', 'Ladder Barrel', 'intermediario', 'decúbito lateral', 'mobilidade lateral e controle oblíquo', 'cadeia lateral, coluna torácica, quadril', 'apoiar lateralmente no barrel, pés fixos', 'inclinar e retornar lateralmente com controle', 'crescer pelas costelas, evitar rotação', 'ângulo inclinação, alinhamento tronco, quadril', 'rodar tronco, tensionar pescoço', 'dor lombar/costal aguda', 'side bend no mat', 'amplitude maior', NULL),
('barrel_horseback', 'Cavalo no Barrel', 'Horseback', 'Barrel', 'Ladder Barrel/Arc Barrel', 'avancado', 'sentado em flexão', 'controle de flexão de coluna e adutores', 'core, cadeia posterior, coordenação', 'sentar no barrel com pernas organizadas', 'arredondar coluna e sustentar controle', 'manter curva uniforme, ombros soltos', 'curvatura coluna, estabilidade, simetria pernas', 'colapsar cervical, prender respiração', 'osteoporose importante, dor lombar aguda', 'spine stretch', 'horseback com carga/variação', NULL),
('access_magic_circle_adduction', 'Adução com círculo', 'Magic Circle Adduction', 'Acessórios', 'Magic Circle', 'iniciante', 'sentado ou supino', 'ativação adutores e controle pélvico', 'quadril, assoalho pélvico indireto, simetria', 'posicionar círculo entre joelhos ou tornozelos', 'comprimir e soltar com controle', 'respirar, manter pelve neutra, evitar tensão cervical', 'simetria joelhos, ritmo, postura', 'prender respiração, inclinar tronco', 'dor púbica/quadril', 'menor pressão', 'combinar com ponte', NULL),
('access_band_row', 'Remada com faixa', 'Band Row', 'Acessórios', 'Faixa elástica', 'iniciante', 'sentado ou em pé', 'controle escapular e força dorsal', 'ombro, postura torácica', 'fixar faixa à frente ou segurar com pés', 'tracionar cotovelos para trás com escápulas controladas', 'pescoço longo, peito aberto, costelas estáveis', 'simetria braços, elevação ombros, postura', 'elevar ombros, hiperextender lombar', 'dor ombro, parestesia', 'faixa leve', 'ajoelhado/em pé com desafio', NULL),
('access_ball_bridge', 'Ponte na bola', 'Bridge on Ball', 'Acessórios', 'Bola suíça', 'intermediario', 'decúbito dorsal pés na bola', 'estabilidade lombo-pélvica e posterior de coxa', 'equilíbrio, glúteos, isquiotibiais', 'pés ou panturrilhas apoiadas na bola', 'elevar quadril controlando instabilidade', 'pelve nivelada, bola quieta, joelhos alinhados', 'oscilação bola, altura pelve, simetria', 'perder alinhamento, cãibra, lombar arqueada', 'risco queda, dor lombar', 'ponte no mat', 'curl de isquios na bola', NULL),
('access_foam_roller_dead_bug', 'Dead bug no rolo', 'Foam Roller Dead Bug', 'Acessórios', 'Foam roller', 'intermediario', 'decúbito dorsal sobre rolo', 'controle anti-rotação e estabilidade', 'core, equilíbrio, dissociação MMSS/MMII', 'deitar longitudinalmente sobre rolo', 'alternar braços/pernas mantendo tronco estável', 'respiração calma, pelve e costelas controladas', 'oscilação tronco, simetria, amplitude membros', 'cair para lado, prender respiração', 'baixa tolerância ao equilíbrio', 'cabeça apoiada no mat', 'alavancas longas', NULL),
('clinical_sit_to_stand', 'Senta e levanta inspirado no Pilates', 'Pilates-based Sit to Stand', 'Clínico funcional', 'Cadeira/Mat', 'iniciante', 'sentado para em pé', 'função, força e controle de MMII', 'idosos, pós-operatório, equilíbrio', 'sentar na borda da cadeira com pés paralelos', 'levantar e sentar com controle', 'nariz sobre os dedos, joelhos alinhados, coluna longa', 'tempo, simetria, valgo, inclinação tronco', 'usar impulso, desabar no assento, assimetria', 'dor torácica, tontura, queda', 'apoio de mãos', 'sem mãos/carga', NULL),
('clinical_wall_roll_down', 'Rolamento na parede', 'Wall Roll Down', 'Clínico contemporâneo', 'Parede', 'iniciante', 'em pé com apoio na parede', 'consciência postural e mobilidade', 'coluna, respiração, relaxamento', 'ficar com costas próximas à parede', 'puxar queixo e enrolar coluna lentamente', 'soltar ombros, respirar, respeitar amplitude', 'curvatura coluna, simetria, amplitude', 'flexionar só cervical, travar joelhos', 'tontura, osteoporose sem adaptação', 'menor amplitude', 'sem parede', NULL),
('clinical_balance_reach', 'Alcance em equilíbrio', 'Balance Reach', 'Clínico funcional', 'Sem equipamento', 'iniciante-intermediario', 'em pé unilateral ou semi-tandem', 'equilíbrio e controle postural', 'prevenção quedas, tornozelo/quadril', 'ficar em base segura próxima a apoio', 'alcançar braços ou perna sem perder alinhamento', 'olhar estável, quadril nivelado, joelho macio', 'oscilação, tempo apoio, alinhamento joelho-pé', 'prender respiração, agarrar dedos, compensar tronco', 'risco de queda alto', 'apoio bilateral', 'unipodal com alcance multidirecional', NULL),
('clinical_breathing_rib_cage', 'Respiração costal orientada', 'Lateral Breathing', 'Clínico contemporâneo', 'Mat', 'iniciante', 'supino/sentado', 'coordenação respiratória e controle costal', 'educação respiratória, postura, dor', 'posicionar mãos nas costelas laterais', 'inspirar expandindo lateralmente e expirar fechando costelas', 'pescoço relaxado, sem elevar ombros', 'elevação ombros, movimento torácico, ritmo', 'respiração apical, tensão cervical', 'dispneia, dor torácica, tontura', 'posição confortável', 'integrar com movimento', NULL)
on conflict (id) do nothing;